FROM ubuntu

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
    sudo \
    curl wget \
    git \
    jq \
    dos2unix \
    mysql-client \
    tzdata \
    rsync \
    nano \
    unzip \
    knockd \
    python3.8 \
    python3-pip \
    && apt-get clean


COPY api/ /data/

COPY startup.sh /data/

EXPOSE 8080

RUN python3 -m pip install -r /data/requirements.txt

VOLUME ["/data"]
WORKDIR /data

STOPSIGNAL SIGTERM

CMD ["sh", "startup.sh"]
