FROM alpine

RUN apk add \
    curl wget \
    mysql-client \
    nano \
    python3 \
    py3-pip

COPY api/ /data/

COPY startup.sh /data/

EXPOSE 8000

RUN python3 -m pip install -r /data/requirements.txt

VOLUME ["/data"]
WORKDIR /data

STOPSIGNAL SIGTERM

CMD ["sh", "startup.sh"]
